default: check test

check:
    moon check --deny-warn

test:
    moon test

test-update:
    moon test --update

run:
    moon run examples/20260320-curl-moonbit

fmt:
    moon fmt

clean:
    moon clean
