# PoC: struct-first closure setter

default:
    just --list

build:
    moon build --target native examples/20260314-sf-a-closure

test:
    moon test --target native examples/20260314-sf-a-closure

run:
    moon run --target native examples/20260314-sf-a-closure
