#!/usr/bin/env bash
# gen-completion-templates.sh — spec templates/completion.{zsh,bash,fish} を
# src/kuu/completion_templates.mbt へ転写する (DR-117 §2.5 + findings §2 / M2)。
#
# 経路 (findings §2.2 転写 + 同期検査、UXL-Q2=a 裁定):
#   1. spec リポの templates/ を読む (default = ../../kuu/main、KUU_SPEC で上書き可)
#   2. 各 shell テンプレを MoonBit の `#|` raw string literal 行に写す
#      (`#|` 直後の空白は verbatim。行間は \n で連結、末尾は空 #| で trailing \n)
#   3. src/kuu/completion_templates.mbt を全上書き
#
# 決定的出力: 同一入力なら byte-identical な出力を生成する。
# 検査経路: `just check-templates` が (1) tempcopy → (2) 再生成 → (3) diff で drift を検知。
#
# テンプレ変数 {{BINARY}} / {{PROGRAM_NAME}} / {{UUID}} は generate_completion_script()
# が呼び出し時に literal 置換する (src/kuu/completion.mbt、M3)。

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$here/.." && pwd)"
default_spec_root="$repo_root/../../kuu/main"
spec_root="${KUU_SPEC:-${1:-$default_spec_root}}"

# 絶対パス化
if [ ! -d "$spec_root" ]; then
  echo >&2 "Error: spec repo directory not found: $spec_root"
  echo >&2 "  Pass KUU_SPEC=<path> or first positional argument (default: $default_spec_root)"
  exit 1
fi
spec_root="$(cd "$spec_root" && pwd)"
spec_templates="$spec_root/templates"
if [ ! -d "$spec_templates" ]; then
  echo >&2 "Error: templates/ not found under spec repo: $spec_templates"
  exit 1
fi

zsh_src="$spec_templates/completion.zsh"
bash_src="$spec_templates/completion.bash"
fish_src="$spec_templates/completion.fish"
for f in "$zsh_src" "$bash_src" "$fish_src"; do
  if [ ! -f "$f" ]; then
    echo >&2 "Error: expected template not found: $f"
    exit 1
  fi
done

output="$repo_root/src/kuu/completion_templates.mbt"

# emit_fn: pub fn <name>() -> String { #|<line>... #| } を書き出す
# 引数: $1=fn_name  $2=template_file  $3=basename_for_doc
emit_fn() {
  local fn_name="$1"
  local file="$2"
  local basename="$3"
  printf '\n'
  printf '///|\n'
  printf '/// Transcribed from spec `templates/%s` (DR-117 §4 wire + §3 env protocol).\n' "$basename"
  printf '/// Regenerated by `scripts/gen-completion-templates.sh` — do not edit by hand.\n'
  printf '/// Variables `{{BINARY}}` / `{{PROGRAM_NAME}}` / `{{UUID}}` are literal-substituted by\n'
  printf '/// `generate_completion_script()` at capability call time (DR-117 §2.5).\n'
  printf 'pub fn %s() -> String {\n' "$fn_name"
  # 直接 body に置くと MoonBit 0027 (deprecated_syntax) が出るため `()` で包む。
  # `#|` 行間は \n 連結、末尾は空 `#|` で trailing \n を付ける。
  printf '  (\n'
  # Read file line by line, prefix each with '    #|' (4-space indent + marker verbatim tail)
  # POSIX `read -r` drops trailing '\n'. `|| [ -n "$line" ]` catches a final line missing '\n'.
  while IFS= read -r line || [ -n "$line" ]; do
    printf '    #|%s\n' "$line"
  done < "$file"
  # trailing '\n' at end of the emitted script: append one empty '#|' line
  printf '    #|\n'
  printf '  )\n'
  printf '}\n'
}

{
  printf '// completion_templates.mbt — DR-117 shell glue templates transcribed from spec `templates/`.\n'
  printf '//\n'
  printf '// generated by scripts/gen-completion-templates.sh from spec templates/\n'
  printf '// DO NOT EDIT MANUALLY — run `just gen-templates` to regenerate.\n'
  printf '//\n'
  printf '// Purpose (findings 2026-07-23-completion-ux-layer-plan §2, UXL-Q2=a): spec リポ\n'
  printf '// `templates/` を language-neutral な正本とし、実装リポは vendoring (転写) + 同期検査\n'
  printf '// (`just check-templates`) で drift を防ぐ。テンプレ変数 `{{BINARY}}` /\n'
  printf '// `{{PROGRAM_NAME}}` / `{{UUID}}` は generate_completion_script() (completion.mbt) が\n'
  printf '// capability 呼び出し時に literal 置換する (DR-117 §2.5)。\n'
  emit_fn "completion_template_zsh"  "$zsh_src"  "completion.zsh"
  emit_fn "completion_template_bash" "$bash_src" "completion.bash"
  emit_fn "completion_template_fish" "$fish_src" "completion.fish"
} > "$output"

echo "Wrote $output"
